default:
	gcc -o lab3a -g -Wall -Wextra lab3a.c

dist: default
	tar -czvf lab3a-005154394.tar.gz lab3a.c Makefile README ext2_fs.h P3A_check.sh trivial.csv trivial.img EXT2_test.img

clean:
	rm -f lab3a-005154394.tar.gz lab3a
